### ISSUE TITLE
Open Source project off of this?

### ISSUE THREAD

**Issue by chrisbbreuer** [laracasts/Lets-Build-a-Forum-in-Laravel#31]
Is anyone interested in starting an open source project/fork off of this? There are very few good forum packages available, and from the few there are, there are even fewer actively maintained.

Ideas?

**Comment by medic917** [comment]
Hey Chris, any progress on this idea? I noticed the council project you've forked and was curious about that too.

**Comment by chrisbbreuer** [comment]
@medic917 Jeff started https://github.com/JeffreyWay/council off of this. 
You can view the series here https://laracasts.com/series/how-to-manage-an-open-source-project

I guess because of that, this can basically be closed 👍
