### ISSUE TITLE
If a first comment in a thread is favorited, and you try to delete it, it will delete other comments in the thread.

### ISSUE THREAD

**Issue by GabMic** [laracasts/Lets-Build-a-Forum-in-Laravel#5]
I have noticed the following issue after the latest video(37). when you favorite the first reply in a thread(and only in that situation) and try to delete that favorited reply, it just deletes the other replies instead. here is a gif to illustrate the situation a am having. 
![comment](https://cloud.githubusercontent.com/assets/11059876/26007206/2c5a046c-3748-11e7-9436-cec76cb9faba.gif)

**Comment by JeffreyWay** [comment]
This is fixed in episode 38.
