### ISSUE TITLE
Channels dropdown doesn't show channels anymore

### ISSUE THREAD

**Issue by kasperpeulen** [laracasts/Lets-Build-a-Forum-in-Laravel#8]
![image](https://cloud.githubusercontent.com/assets/1035299/26009084/997382c2-3747-11e7-940e-fb8621a6fb00.png)

**Comment by kasperpeulen** [comment]
I think now I understand:

```
      \View::composer('*', function ($view) {
            $channels = \Cache::rememberForever('channels3', function () {
                $channels = Channel::all();
                return $channels;
            });

            $view->with('channels', $channels);
        });
```

My database was not seeded when I started this project, so my channels will now (forever?) be empty. Because `dd($channels)` give an empty collection. Can I reset this cache somehow?

**Comment by n1crack** [comment]
You can call 'php artisan cache:clear'

or you can listen eloquent model events
````
      
public static function boot()
    {
        parent::boot();
        static::created(function ($model)
        {
            // Clear Cache commands
        });
    }
````
